### PR TITLE
Spectre redesign

### PR DESCRIPTION
**Pull request by dom96**
screen shot 2017-08-19 at 19 24 46

### CODE REVIEW

**Comment by dom96** [comment]
There are still many TODOs left. I wasn't able to show a lot of data, for example for the most queried packages all the templates get are the names of the packages, it would be nice to get the username of the author, the avatar etc. See the code for more.

**Comment by euantorano** [comment]
Looks really nice so far!

The spacing of the header links looks a little bit off in the screenshot - there seems to be more space to the right of `Twitter` than there is to the right of `GitHub`.

Also, the search box at the top seems to have rounded corners on the left side, but the button to the right doesn't have rounder corners, which looks slightly odd in my opinion.

**Comment by dom96** [comment]
> The spacing of the header links looks a little bit off in the screenshot - there seems to be more space to the right of Twitter than there is to the right of GitHub.

Hrm, indeed. Will look into that later :)

> Also, the search box at the top seems to have rounded corners on the left side, but the button to the right doesn't have rounder corners, which looks slightly odd in my opinion.

Huh, it does have rounded corners? Only on the right side though. In order for the button to be "stuck" to the search box the sides which are touching are not rounder which makes sense.

**Comment by euantorano** [comment]
>Huh, it does have rounded corners? Only on the right side though. In order for the button to be "stuck" to the search box the sides that are touching are not rounded which makes sense.

So it does, it just wasn't quite as obvious. I'd remove the right border from the search box though since I'm looking at it again - at the minute there's a very faint grey border between the box and button.

**Comment by dom96** [comment]
That's a Spectre thing. Best to hit their repo with an issue for that ;)

**Comment by euantorano** [comment]
Ah, I'll do so now thanks.

**Comment by euantorano** [comment]
The issue with the border on the search box is apparently fixed in [v0.3.2](https://github.com/picturepan2/spectre/releases/tag/v0.3.2) of Spectre, it may be worth updating to the new verison.

**Comment by FedericoCeratto** [comment]
Updated to 0.3.2

**Pull request merged**
