### PR TITLE
Restyle n. 3

### PR DESCRIPTION
**Pull request by Willyboar**
Let's do it. :)

### CODE REVIEW

**Comment by FedericoCeratto** [comment]
Contributors and user: can you please vote?

Main page:  https://nimble.directory/ VS https://prnt.sc/suy0hx
Package page: https://nimble.directory/pkg/rosencrantz VS https://prnt.sc/suy5sv 
Thumbs up: change
Thumbs down: keep

**Comment by Willyboar** [comment]
After change to two column layout, made some allignments for @supakeen and fix the media:

Browse/Search Page:
a1

Index/Home Page:
a2

Package Page:
a3

**Comment by Willyboar** [comment]
Package Page after some Fixes:

a4

**Comment by RSDuck** [comment]
I hope this doesn't come off as too pedantic, but do the package names and descriptions both need to be bold? The round bubbly buttons in general sometimes look to me a bit to big compared to the rest of the text.

**Comment by Willyboar** [comment]
There is a max-width 1200px. The space on the sides is probably because of my screen. It is a common limit to most web sites.

**Comment by moigagoo** [comment]
I'm all for a redesign, to refresh the looks. But it's also an opportunity to fix some usability issues.

1. Do we need all those available versions? This block takes a lot of space all the time, but do you need this information all the time? Or at all?

2. In the new design, the headings compete with each other. There are all very similar in visual weight, and it's not obvious which one is the most important.

3. Package description is grey on white whereas package description is pretty important.

**Comment by dizzyliam** [comment]
I agree with @RSDuck that the rounded corners are too much. Perhaps cut them down to 6-16dp?

**Comment by digitalcraftsman** [comment]
Thank you @Willyboar for offering a redesign of Nim's package directory. Here are my two cents. Hopefully, me feeded isn't perceived as beeing nitpicky.

The blocks for the package information on the homepage take up a lot of space while visually being quite empty when theme doesn't provide a theme description. Therefore I would suggest a three-column layout to display the most queried, newest and trending packages a more comapt way, similar to https://hex.pm/ and https://crates.io/. As others already stated, the corners for the blocks look a bit too round.

Regarding the package page: the header with meta information such as the author, package versions, tags etc. takes up a lot of space as well. What are visitors probably most interest in is the README provided further down on the page. This however requires a lot of scrolling. What do you about moving the header area into a sidebar, similar to https://crates.io/crates/newline-converter ?

In general I wouldn't mind if the color palette and design converges a bit closer to the website of [Nim](https://nim-lang.org/) itself.

For polls on Github I can recommend [www.gh-polls.com](https://gh-polls.com/). This allows more voting options and is more flexible than a thumb up / down.

**Comment by FedericoCeratto** [comment]
The list of package version will be shortened to 5 latest versions later on.

**Comment by FedericoCeratto** [comment]
The sidebar in https://crates.io/crates/newline-converter is similar to the current package view https://nimble.directory/pkg/moe and I find it allows showing more content.

**Comment by Willyboar** [comment]
This is an alternative with sidebar in the package page:

a1

**Comment by digitalcraftsman** [comment]
The sidebar sidebar look great, with a slight visual preference a 9-3 ratio.

IMHO links like the project website, docs and hosted docs (right now in the sidebar) would be more important than tags/categories. How about swapping them?

The red buttons/links in the sidebar stand out quite a bit. Also red is signaling an alert or danger.  Perhaps a slightly less subtle color tone would be more suiting.

The area in the top right below the dark navigation bar looks a bit empty. Any ideas of how to fill this area?

**Comment by dizzyliam** [comment]
Another thing that would be nice for this redesign is the ability to display images from README (example: [https://nimble.directory/pkg/inumon](https://nimble.directory/pkg/inumon)).

**Comment by Willyboar** [comment]
This happens because you display the logo direct from a PNG inside the repo. You should try upload it in raw and use the link. You can do this by draging and droping the image in a new issue form or even in this comment form and GitHub will produce the link for you.

**Comment by Willyboar** [comment]
@rockcavera thanks for the feedback. Let's take it one by one:

1.The description in the main page was not available from the backend. I think is something @FedericoCeratto can easily fix it.

2 & 3. Agree

4.4.1)Personally i prefer this 2 to be at the top because on the mobile view the sidebar moves at the bottom. Also tags are search links and you can quickly search something similar. 4.2) Me too. 4.3) Well it's not totally red, they are dark orange  😛 .

5.I tried the new design to be full responsive. I check it a lot and i hope to work great. Otherwise we are here to fix the issues.

**Comment by digitalcraftsman** [comment]
@Willyboar are there any plans to add a dark-mode to the website? The [ prefers-color-scheme CSS media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) has already wide support in modern browsers and operating systems.

**Comment by Willyboar** [comment]
@digitalcraftsman not from me. But from what I know @FedericoCeratto  is open to further suggestions and PRs.

**Comment by liquid600pgm** [comment]
image
The cards here could use a smaller font size for the title, and a smaller corner radius, also increasing the blur on the box shadow to make it more soft would help.

**Comment by FedericoCeratto** [comment]
@Willyboar when doing a full/cold reload the page loads with one font style and than changes. It's probably due the order of loading some CSS. Can it be fixed?

**Comment by Willyboar** [comment]
I will check it tomorrow along with some changes I want to do to buttons. I am away from my computer.

**Comment by FedericoCeratto** [comment]
Well, people seem to like the restyle so I'll merge and deploy it as it is. Thank you! I'll make few tweaks and new changes can go in a new PR.

**Pull request merged**
